### ISSUE TITLE
traceback comment error

### ISSUE THREAD

**Issue by shadow11001** [simonegiacomelli/proxmox-firewall-updater#1]
Getting the following error when running script. I have used the #resolve comment in an alias with a proper domain name.

```
Traceback (most recent call last):
  File "/root/update_firewall_aliases.py", line 153, in <module>
    main()
  File "/root/update_firewall_aliases.py", line 149, in main
    update_aliases(ProdDependencies(args))
  File "/root/update_firewall_aliases.py", line 51, in update_aliases
    aliases = [entry for entry in deps.alias_list() if entry.domain() is not None]
                                  ^^^^^^^^^^^^^^^^^
  File "/root/update_firewall_aliases.py", line 116, in alias_list
    return alias_list_to_typed(run.stdout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/update_firewall_aliases.py", line 100, in alias_list_to_typed
    return [AliasEntry(name=alias['name'], cidr=alias['cidr'], comment=alias['comment']) for alias in j]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/update_firewall_aliases.py", line 100, in <listcomp>
    return [AliasEntry(name=alias['name'], cidr=alias['cidr'], comment=alias['comment']) for alias in j]
                                                                       ~~~~~^^^^^^^^^^^
KeyError: 'comment'

```

**Comment by simonegiacomelli** [comment]
Hey thank you for reporting this issue!
I added a test case for handling entries without comments.

Could you try the new version 2.0.6 to see if it is fixed?

**Comment by simonegiacomelli** [comment]
Closing as fixed due to no further feedback. Thank you for notifying me of the issue.
